{
 "title": "Estadísticas general (UCMHo)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General Analisys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  sum(bytes) AS \"Bytes\"\nFROM reports\nWHERE\n  $__timeFilter(time) AND NOT code_status like 'TCP_DENIED%'"
    }
   ]
  },
  {
   "title": "Top Client IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  UNIX_TIMESTAMP(time) AS \"time\",\n  remotehost,\n  SUM(bytes) AS \"Total\"\nFROM reports\nWHERE \n  $__timeFilter(time) AND NOT code_status like 'TCP_DENIED%'\nGROUP BY remotehost\nORDER BY Total desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Top Client Usuario",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  UNIX_TIMESTAMP(time) AS \"time\",\n  rfc931,\n  SUM(bytes) AS \"Total\"\nFROM reports\nWHERE \n  $__timeFilter(time) AND NOT code_status like 'TCP_DENIED%' AND NOT rfc931 like '%-%'\nGROUP BY remotehost\nORDER BY Total desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Top Site",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT \n  UNIX_TIMESTAMP(time) AS \"time\",\n  url,\n  count(url) AS \"value\"\nFROM reports\nWHERE \n  $__timeFilter(time) AND NOT code_status like 'TCP_DENIED%' AND NOT url like '%mozilla%' AND NOT url like '%firefox%' AND NOT url like '%r3.o.lencr.org%' AND NOT url like \"%localhost%\"\nGROUP BY url\nORDER BY value desc\nlimit 1",
     "timeField": "real_timestamp"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Events\"\nFROM reports\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Squid Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  code_status AS metric,\n  count(code_status) AS \"value\"\nFROM reports\nWHERE\n  $__timeFilter(time) AND NOT url like '%mozilla%' AND NOT url like '%firefox%' AND NOT url like '%r3.o.lencr.org%'\nGROUP BY 1, 2\nOrder by 1"
    }
   ]
  },
  {
   "title": "Denied Access",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  remotehost AS metric,\n  count(code_status) AS \"value\"\nFROM reports\nWHERE\n  $__timeFilter(time) and code_status like 'TCP_DENIED/%' AND NOT url like '%mozilla%' AND NOT url like '%firefox%' AND NOT url like '%r3.o.lencr.org%'\nGROUP BY 1, 2\nOrder by 1"
    }
   ]
  },
  {
   "title": "Hits of client",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  remotehost AS metric,\n  count(id) AS \"value\"\nFROM reports\nWHERE\n  $__timeFilter(time)\nGROUP BY metric\nOrder by value desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Hits of User",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  rfc931 AS metric,\n  count(id) AS \"value\"\nFROM reports\nWHERE\n  $__timeFilter(time)\nGROUP BY metric\nOrder by value desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "Megabyte Traffic" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  sum(bytes) AS \"Traffic\"\nFROM reports\nWHERE\n  $__timeFilter(time) AND\n  code_status NOT LIKE 'TCP_DENIED%'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Traffic by Client",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  remotehost AS metric,\n  sum(bytes) AS \"value\"\nFROM reports\nWHERE\n  $__timeFilter(time) AND NOT code_status like 'TCP_DENIED%'\nGROUP BY metric\nOrder by value desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Traffic by Client",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  rfc931 AS metric,\n  sum(bytes) AS \"value\"\nFROM reports\nWHERE\n  $__timeFilter(time) AND NOT code_status like 'TCP_DENIED%'\nGROUP BY metric\nOrder by value desc\nlimit 10"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Top Sites by Hits",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  url,\n  count(url) AS \"value\"\nFROM reports\nWHERE\n  $__timeFilter(time) AND NOT url like '%mozilla%' AND NOT url like '%firefox%' AND NOT url like '%r3.o.lencr.org%' AND NOT url like '%localhost%'\nGROUP BY url\nORDER BY value desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Top Sites by Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  url,\n  sum(bytes) AS \"value\"\nFROM reports\nWHERE\n  $__timeFilter(time) AND NOT code_status like 'TCP_DENIED%' AND NOT url like '%mozilla%' AND NOT url like '%firefox%' AND NOT url like '%r3.o.lencr.org%'\nGROUP BY url\nORDER BY value desc\nlimit 10"
    }
   ]
  }
 ]
}